#!/data/data/com.termux/files/usr/bin/bash
clear
echo -e " \e[92mTermux - Ubuntu "
echo ""
echo -e "   \e[31m██╗  ██╗███╗   ███╗ ██████╗ ██████╗ ██████╗ ███████╗██████╗      "
echo -e "   \e[32m╚██╗██╔╝████╗ ████║██╔═══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗   "
echo -e "    \e[33m╚███╔╝ ██╔████╔██║██║   ██║██║  ██║██║  ██║█████╗  ██████╔╝     "
echo -e "    \e[34m██╔██╗ ██║╚██╔╝██║██║   ██║██║  ██║██║  ██║██╔══╝  ██╔══██╗     "
echo -e "   \e[35m██╔╝ ██╗██║ ╚═╝ ██║╚██████╔╝██████╔╝██████╔╝███████╗██║  ██║    "
echo -e "   \e[36m╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝     "
echo -e "\e[39m"
if [ -e usr/bin/sudo ];
then
cd && cd ~/.ubuntu && sudo bash start.sh
else
cd && cd ~/.ubuntu && bash start.sh
fi
exit
